# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-27 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190327_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='writer',
            new_name='author',
        ),
    ]
