# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-31 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190331_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video',
            new_name='img',
        ),
    ]
